#!/bin/bash


##########################################################################
## Code for generating initial conditions for an unwrapable nucleosomal
## fibre

## New for version 4.0, a fix of the end bead for twistable DNA, which should
## now use a different scheme:
## N-2 to N-1 with usual polytorsion
## N-1 to N with polytorsion but k_tw=0.
## Also add a bead at the centre of the nucleosome

## This version 4.0 correclty sets the relative orientation of neighbouring
## nucleosomes depending on the linker length.
## Linkers are whole numbers of beads, so can be multiples of 5bp
## See dir neigh_nuc_angle_testing/ for how the required angles were found.

######################
## Compile the code

make

######################
## Run the code

# without arguments to get some help
./generate_ic

# to generate an initial condition file
./generate_ic -f data.lammps -s 545646 -e 1 -N 10 -L1 5 -L 8 -LF 5

# for this work always use -e 1
# typical linker length for inactive chromatin 40bp (8 beads)


######################
## Run a simulation

~/path/to/lmp_mpi < in.lammps_twistable_nucInteractions


## this incudes an equilibration phase, where different parts of the
## model are switched on sequentailly.
## For initial testing, can shorten the run-time of some of these steps


######################
## Some vmd commands to get things looking nice -- open Tk console and paste in

mol modselect 0 0 type 1
mol modcolor 0 0 ColorID 15
mol modstyle 0 0 VDW 1.000000 42.0
mol modmaterial 0 0 AOChalky

mol addrep 0
mol modselect 1 0 type 2
mol modcolor 1 0 ColorID 23
mol modstyle 1 0 VDW 1.000000 42.0
mol modmaterial 1 0 AOChalky

mol addrep 0
mol modselect 2 0 type 3
mol modcolor 2 0 ColorID 2
mol modstyle 2 0 VDW 1.000000 42.0
mol modmaterial 2 0 AOChalky

mol addrep 0
mol modselect 3 0 type 4
mol modcolor 3 0 ColorID 2
mol modstyle 3 0 VDW 1.365232 42.0
mol modmaterial 3 0 AOChalky

mol addrep 0
mol modselect 4 0 type 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22
mol modcolor 4 0 ColorID 4
mol modstyle 4 0 VDW 0.5 42.0
mol modmaterial 4 0 Transparent
